import '../vendor/jquery.min.js';
import '../vendor/jquery.mockjax.js';
import '../vendor/store-js.js';
import Raphael from '../vendor/raphael.min.js';
import '../vendor/qunit.js';
import './application';
import './event';
import './manager';
import './page';
import './status';
